name: CustomHelp
version: ${project.version}
main: com.geronimomc.Main
api-version: 1.14
authors: [Simon_Xz]
description: Custom Help
website: https://discord.geronimomc.com

commands:
  help:
    description: Shows the custom help
    usage: /<command>
  grcore:
    description: Reloads the config
    usage: /<command>